# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-13 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='route',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Route'),
            preserve_default=False,
        ),
    ]
