# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-13 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together=set([('route', 'order')]),
        ),
    ]
