# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-15 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='backwards_loop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='current',
            name='travel_forward',
            field=models.BooleanField(default=True),
        ),
    ]
